# Podfile

use_modular_headers!

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1' # Set a specific iOS version, e.g., '13.4'
prepare_react_native_project!

# Use static frameworks for all pods. This is required for React Native Firebase
# and helps avoid many common integration issues.
use_frameworks! :linkage => :static

target 'RuralShareApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # This hook is a workaround for certain pods (like Flipper)
  # that have trouble with the 'use_frameworks!' directive.
  pre_install do |installer|
    $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly', 'CocoaAsyncSocket', 'ComponentKit', 'RCT-Folly', 'Yoga', 'boost', 'glog', 'DoubleConversion']
    installer.pod_targets.each do |pod|
      if $static_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end